name: Check News

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  check-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 添加写入权限
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ github.token }}  # 使用自动生成的 token
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 python-telegram-bot
    
    - name: Run news checker
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python src/main.py 
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add news.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update news.json" && git push)